import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Provider } from './Provider'
import NavBar from './ui/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AU Vans',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.className}>
      <Provider>
        <body className='flex flex-col min-h-screen'>
          <NavBar/>
          <div className="flex-grow bg-gray-200">
           {children}
          </div>
          
          <footer className=" text-black py-4">
            <div className="container mx-auto text-center">
              <p className="text-sm">
                &copy; {new Date().getFullYear()} AU Vans. All rights reserved.
              </p>
              <p className="text-sm">
                Developed by{' '}
                NoelPOS
              
              </p>
            </div>
          </footer>
        </body>
      </Provider>
    </html>
  )
}
